### ISSUE TITLE
All pathnames are pointing to /index.php

### ISSUE THREAD

**Issue by Ekion-1** [philkra/elastic-apm-laravel#15]
Is there a way to get the package to get the endpoint that the user went to for GET and POST requests, rather than the Laravel entry point?

**Comment by philkra** [comment]
I'm not sure I understand this correctly, by default when a request comes in the APM creates a transaction with the name e.g. `GET /news/1234/more-slug/`. In other words, `HTTP_METHOD URI_PATH`. Is that the endpoint you are referring to, or can you elaborate what you mean with the laravel endpoint?

**Comment by Ekion-1** [comment]
If I make a POST request to `/users/register` within my app, I cannot see the endpoint in Kibana. I only see a POST was made to `/index.php` (the entry point of Laravel).

**Comment by Ekion-1** [comment]
Apologies, it was shown in the ENV section I just missed it.

**Comment by Ekion-1** [comment]
Actually, with that being said, is there a way to remove sensitive .env data from being sent to Kibana?

**Comment by philkra** [comment]
yes, there is an option to mask the `env` data, it was actually released just last week https://github.com/philkra/elastic-apm-php-agent#example-of-an-extended-configuration

**Comment by Ekion-1** [comment]
Thanks. How do I use the extended configuration? The documentation does a good job of telling me what it is but not how to use it.

**Comment by philkra** [comment]
mea culpa, @jblotus raised a good point with the issue https://github.com/philkra/elastic-apm-laravel/issues/17 where the client version `6.2.*` is used and this features was introduced in `6.4.*`
