### ISSUE TITLE
Use of undefined constant LARAVEL_START with PHPUnit Tests

### ISSUE THREAD

**Issue by Ekion-1** [philkra/elastic-apm-laravel#16]
I'm receiving this error from line 135 in ElasticApmServiceProvider when running tests. Is this a known issue? How would I selectively remove the middleware from Kernel.php when running tests?

**Comment by Ekion-1** [comment]
I solved this by adding `$this->withoutMiddleware(\PhilKra\ElasticApmLaravel\Middleware\RecordTransaction::class);` to my `TestCase.php` `setUp()` method.

**Comment by Ekion-1** [comment]
I assumed the above fixed the issue, but it's happening again even with the above workaround. Looking into it now.

**Comment by Ekion-1** [comment]
Replacing `LARAVEL_START` in `ElasticApmServiceProvider.php` with `microtime(true)` seemed to fix the issue. Do you have any idea why it can't find the declared constant in `bootstrap/autoload.php`?

**Comment by philkra** [comment]
That's odd! How are you running your unit tests? Are you bootstrap'ing the aoutload in the phpunit call? Can you paste your phpunit.xml?

**Comment by philkra** [comment]
Can you please paste the command you're executing and your phpunit.xml?

**Comment by jblotus** [comment]
a defined check inside the service provider might be good as well

**Comment by philkra** [comment]
James, yes and no, we can debate if it makes sense to have the APM agent active during unit tests :) 
I'm more curious why this const isn't bootstraped by the framework.

**Comment by jblotus** [comment]
I actually would like the option to have the agent on during tests just from an integration standpoint. I'm also curious about why that is not bootstrapped by default.

**Comment by philkra** [comment]
@AlexGodbehere can you please post your `phpunit.xml` and the command you are calling the unit test(s) in order to get to the bottom of this?

**Comment by jblotus** [comment]
define('LARAVEL_START', microtime(true));

is only defined in artisan or index.php for the webroot

it is not defined for tests when running with vendor/bin/phpunit command

you can add the following to your TestCase.php and it will also fix the issue

```php
   if (!defined('LARAVEL_START')) {
            define('LARAVEL_START', microtime(true));
        }
```

**Comment by philkra** [comment]
I'm hesitant to include this patch since, I would suggest to run unit tests in Laravel the laravel-way with `artisan`.

**Comment by Ekion-1** [comment]
> @AlexGodbehere can you please post your `phpunit.xml` and the command you are calling the unit test(s) in order to get to the bottom of this?

Apologies for the slow reply. I'll get you a copy when I get home from work tonight. By the sounds of it, @jblotus comment is likely why the constant isn't being bootstrapped. I'm running tests via phpunit.

Edit: phpunit.xml attached:

```
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="vendor/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>

        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
        <env name="BROADCAST_DRIVER" value="log"/>
    </php>
</phpunit>
```

**Comment by jblotus** [comment]
I've been looking for documentation on running tests the laravel way and until now I actually didn't know running via artisan was an option. I assumed that running the following was kind of normal across frameworks.

```
vendor/bin/phpunit
```

**Comment by Ekion-1** [comment]
Adding the following to the `setUp()` method of TestCase doesn't seem to help with the problem, which is strange.

```
if (!defined('LARAVEL_START')) {
    define('LARAVEL_START', microtime(true));
}
```

**Comment by philkra** [comment]
hi, sorry for being silent so long, i had a private situation. i'm still the opinion that this shouldn't be included in the agent, i don't see any sense in manually bootstrap'ing laravel "things" when there is a dedicated way of running tests* plus there is a likelihood of creating back- and forward compatibility problems. 

* https://laravel.com/docs/5.7/testing#creating-and-running-tests

**Comment by philkra** [comment]
> Adding the following to the `setUp()` method of TestCase doesn't seem to help with the problem, which is strange.
> 
> ```
> if (!defined('LARAVEL_START')) {
>     define('LARAVEL_START', microtime(true));
> }
> ```

you should check out the phpunit documentation*, the `setUp()` method is called before every `test*` method, at this stage it's too late to define the constant. in case you want to do such a "thing" you should add this definition to the phpunit bootstraper.

* https://phpunit.readthedocs.io/en/7.4/fixtures.html?highlight=setup#more-setup-than-teardown

**Comment by jblotus** [comment]
My eyes might be deceiving me, but the docs referenced actually just show how to use artisan to make tests. The docs also say:

"Once the test has been generated, you may define test methods as you normally would using PHPUnit. To run your tests, execute the phpunit command from your terminal:"

Hope all is well.
