### ISSUE TITLE
composer.json bump package requirements

### ISSUE THREAD

**Issue by jblotus** [philkra/elastic-apm-laravel#17]
https://github.com/philkra/elastic-apm-laravel/blob/fce1d1d2e927c75d500a1b74282295d80a01e7b8/composer.json#L19

I was having trouble installing without using an alias - this should probably be bumped to 6.4.*

**Comment by philkra** [comment]
Yep, I missed that one! Thanks James, PR https://github.com/philkra/elastic-apm-laravel/pull/18 creates a wildcard'ed minor versioning in order to always get the most recent major version of the client.
