### ISSUE TITLE
Disable on cli due to memory leaks from long running jobs

### ISSUE THREAD

**Issue by jblotus** [philkra/elastic-apm-laravel#19]
Just a quick FYI - we had to disable this from the cli entirely. We were running out of memory due to query/transaction logging from the agent and many of our batch jobs that run using artisan tasks  processed thousands of queries.

You can probably close this but in case someone else came across it I wanted to make people ware.

//we do something like this:
```
'active'        => PHP_SAPI !== 'cli' && env('ELASTIC_APM_ACTIVE', false),
```

**Comment by philkra** [comment]
thank you for the tip, I added this to a knowledge base of the agent (https://github.com/philkra/elastic-apm-php-agent#disable-agent-for-cli)
