### ISSUE TITLE
Laravel 5.5 JSON validation issue

### ISSUE THREAD

**Issue by nebili2023** [philkra/elastic-apm-laravel#2]
While testing we came to an issue with latest version. This is what we got from the logs:

[2018-07-25 11:16:14] qa.ERROR: Client error: `POST http://192.168.50.120:8200/v1/transactions` resulted in a `400 Bad Request` response:
data validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"
  (truncated...)
 {"userId":891267,"email":"n.ilijoski@voxteneo.com.mk","exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST http://192.168.50.120:8200/v1/transactions` resulted in a `400 Bad Request` response:
data validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"
  (truncated...)
 at /var/sites/qa.erasmusplusols.eu/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]

Any idea how to bypass this issue?

**Comment by philkra** [comment]
@nesoman , sorry for the late reply. I'm not sure as I haven't encountered that error yet. What I found was the following https://github.com/elastic/apm-agent-nodejs/issues/141 as well as the following describing the error message: https://github.com/elastic/apm-server/issues/166

**Comment by jblotus** [comment]
FYI i fixed this error by changing my app name in the config to not include spaces - not sure if related
