### ISSUE TITLE
Flush query log on agent send.

### ISSUE THREAD

**Issue by NicklasWallgren** [philkra/elastic-apm-laravel#22]
It's probably a good idea to flush the query-log on agent send, inorder to keep the memory usage in check.

**Comment by philkra** [comment]
that does make sense, I'll need to check if the `send()` method of the `Agent` actually flushed the trace stores. In that case, that would be the solution, otherwise a `flush` method would be required.

**Comment by philkra** [comment]
@NicklasWallgren checkout the release `6.4.2` of the Agent: https://github.com/philkra/elastic-apm-php-agent/releases/tag/v6.4.2

Triggering the send method on the agent reset's/flushed the traces stores.

**Comment by aftabnaveed** [comment]
I am using an application server built in SwoolePHP which keeps the laravel framework in memory and this fix really helped. 

thank you.
