### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by dstepe** [philkra/elastic-apm-laravel#28]
I'd like to get a new release with the config changes I submitted. But before that, I found an inconsistency in the variable naming I want to fix. I'm also adding some configuration documentation. I'll have a PR shortly.

**Comment by dstepe** [comment]
Please see https://github.com/philkra/elastic-apm-laravel/pull/29

**Comment by dstepe** [comment]
And #31

**Comment by poor-bob** [comment]
It's unusable without a new release. I'm not connecting to an elasticsearch database while developing locally.

**Comment by dstepe** [comment]
Can you provide a little more detail? I'm not sure the changes I expect in the next release would change your experience. Are you getting errors because the agent is trying to send to the APM server? If so, have you tried adding `APM_ACTIVE=false` to your .env file?

**Comment by poor-bob** [comment]
I added `APM_ACTIVE=false` to my .env file and it did not change this library's behavior. I had to manually change `'active' => true` to `'active' => false` in `vendor/philkra/elastic-apm-laravel/config/elastic-apm.php`.

This isn't that big of a deal, but I can't merge my branch into master and expect the team to also configure their vendor directory. I assumed that a new release would resolve this as I see that your changes have been merged into master, enabling the use of `APM_ACTIVE` (thank you!)

I'm using version 5.7.3

**Comment by dstepe** [comment]
Of course. Sorry, I forgot at what point that change was made. @philkra are you ready to make a new release? I think I'm done with my changes.

@poor-bob In the mean time, you could use a composer VCS repo to pull the master branch into your project until the new release is available.

**Comment by dstepe** [comment]
@poor-bob You can also publish the config to your project config directory and make any changes you want:

```
php artisan vendor:publish --tag=config --provider="PhilKra\ElasticApmLaravel\Providers\ElasticApmService
Provider"
```
That would make it part of your project distribution and give you complete control. You may have to make changes manually or get a fresh copy if the config options change in the future, though.

**Comment by philkra** [comment]
Hi, the PR #29 is merged. I hope this will solve @poor-bob 's problem. @dstepe thank you for moderating!
