### ISSUE TITLE
Laravel 5.5 $request->route() is null in global middleware

### ISSUE THREAD

**Issue by nebili2023** [philkra/elastic-apm-laravel#3]
This is another issue we got with laravel 5.5. Entire application crashes when we use the default configuration, including the Apm middleware in global middleware in the Kernel.php.

When we added it as route middleware it was working, but still we need it defined globally. What can we do about this issue, any workaround?

**Comment by philkra** [comment]
Oh, I'm sorry. I haven't tested the agent with Laravel `5.5`, solely tested it on version `5.6` as stated in the README.

I'm a little confused where you put what. What error is shown when using the default config? `$request->route() is null in global middleware`.

I haven't check but when you use the Facade `use ElasticApm;` you should be able use it everywhere in you app.

**Comment by philkra** [comment]
@nesoman , so I could reproduce this and I rolled out a bug fix with the release 5.6.2
