### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by Froelund** [philkra/elastic-apm-laravel#36]
We are experiencing an issue when reporting to APM from our laravel app.

```
POST https://APP_ID.apm.eu-central-1.aws.cloud.es.io/v1/transactions` resulted in a `413 Request Entity Too Large`
```

I see there's an config option for limiting the `backtraceDepth`, but can I be sure that limiting this is sufficient?

**Comment by philkra** [comment]
@Froelund , no there is no such option thus far, but there should be! I created an issue in the agent repo for this: https://github.com/philkra/elastic-apm-php-agent/issues/55
