### ISSUE TITLE
Problem output Logstash

### ISSUE THREAD

**Issue by Ddev-scripts** [philkra/elastic-apm-laravel#42]
Hello,
I have a problem with the use of your module.
Previously, I had only one server with all the ELK stack installed on the same server.

But my environment has changed, and I now have to use AWS elasticsearch.

So I have a vps (EC2) with, logstash and apm server.

The configuration of the APM server is different because I have to send the data to the logstash and it sends the data to elasticsearch (AWS).

Unfortunately, I have some errors:

**IN DISCOVER**

`Error with Painless scripted field 'doc['context.service.name'].value'
You can address this error by editing the ‘doc['context.service.name'].value’ field in Management > Index Patterns, under the “Scripted fields” tab.

Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"script_exception","reason":"runtime error","script_stack":["org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:670)","org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:115)","org.elasticsearch.index.query.QueryShardContext.lambda$lookup$0(QueryShardContext.java:280)","org.elasticsearch.search.lookup.LeafDocLookup$1.run(LeafDocLookup.java:88)","org.elasticsearch.search.lookup.LeafDocLookup$1.run(LeafDocLookup.java:85)","java.security.AccessController.doPrivileged(Native Method)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:85)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)","doc['context.service.name'].value","    ^---- HERE"],"script":"doc['context.service.name'].value","lang":"painless"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"fetch","grouped":true,"failed_shards":[{"shard":0,"index":"apm-server-6.4.2-2019.03.20","node":"QWoCwS11TFmuhfUKvNVq-Q","reason":{"type":"script_exception","reason":"runtime error","script_stack":["org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:670)","org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:115)","org.elasticsearch.index.query.QueryShardContext.lambda$lookup$0(QueryShardContext.java:280)","org.elasticsearch.search.lookup.LeafDocLookup$1.run(LeafDocLookup.java:88)","org.elasticsearch.search.lookup.LeafDocLookup$1.run(LeafDocLookup.java:85)","java.security.AccessController.doPrivileged(Native Method)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:85)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)","doc['context.service.name'].value","    ^---- HERE"],"script":"doc['context.service.name'].value","lang":"painless","caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [context.service.name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}}]},"status":500}
`
**AND IN SOME DASHBOARD**

`Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"script_exception","reason":"runtime error","script_stack":["org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:670)","org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:115)","org.elasticsearch.index.query.QueryShardContext.lambda$lookup$0(QueryShardContext.java:280)","org.elasticsearch.search.lookup.LeafDocLookup$1.run(LeafDocLookup.java:88)","org.elasticsearch.search.lookup.LeafDocLookup$1.run(LeafDocLookup.java:85)","java.security.AccessController.doPrivileged(Native Method)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:85)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)","doc['context.service.name'].value","    ^---- HERE"],"script":"doc['context.service.name'].value","lang":"painless"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"fetch","grouped":true,"failed_shards":[{"shard":0,"index":"apm-server-6.4.2-2019.03.20","node":"pQKBqXhXTiS7yrEXwY4GsA","reason":{"type":"script_exception","reason":"runtime error","script_stack":["org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:670)","org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:115)","org.elasticsearch.index.query.QueryShardContext.lambda$lookup$0(QueryShardContext.java:280)","org.elasticsearch.search.lookup.LeafDocLookup$1.run(LeafDocLookup.java:88)","org.elasticsearch.search.lookup.LeafDocLookup$1.run(LeafDocLookup.java:85)","java.security.AccessController.doPrivileged(Native Method)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:85)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)","doc['context.service.name'].value","    ^---- HERE"],"script":"doc['context.service.name'].value","lang":"painless","caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [context.service.name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}}]},"status":500}
    at https://search-elk-project-dqsfqsdfjfdifhdfiu.eu-west-1.es.amazonaws.com/_plugin/kibana/bundles/commons.bundle.js:1:779873
    at Function.Promise.try (https://search-elk-project-dqsfqsdfjfdifhdfiu.eu-west-1.es.amazonaws.com/_plugin/kibana/bundles/commons.bundle.js:1:488441)
    at https://search-elk-project-dqsfqsdfjfdifhdfiu.eu-west-1.es.amazonaws.com/_plugin/kibana/bundles/commons.bundle.js:1:487812
    at Array.map (<anonymous>)
    at Function.Promise.map (https://search-elk-project-dqsfqsdfjfdifhdfiu.eu-west-1.es.amazonaws.com/_plugin/kibana/bundles/commons.bundle.js:1:487770)
    at callResponseHandlers (https://search-elk-project-dqsfqsdfjfdifhdfiu.eu-west-1.es.amazonaws.com/_plugin/kibana/bundles/commons.bundle.js:1:779232)
    at https://search-elk-project-dqsfqsdfjfdifhdfiu.eu-west-1.es.amazonaws.com/_plugin/kibana/bundles/commons.bundle.js:1:765209
    at processQueue (https://search-elk-project-dqsfqsdfjfdifhdfiu.eu-west-1.es.amazonaws.com/_plugin/kibana/bundles/vendors.bundle.js:118:199684)
    at https://search-elk-project-dqsfqsdfjfdifhdfiu.eu-west-1.es.amazonaws.com/_plugin/kibana/bundles/vendors.bundle.js:118:200647
    at Scope.$digest (https://search-elk-project-dqsfqsdfjfdifhdfiu.eu-west-1.es.amazonaws.com/_plugin/kibana/bundles/vendors.bundle.js:118:210409)`

Thanks for reading !

Have a nice day !

**Comment by dstepe** [comment]
I'm not clear how the problem you are describing is attributed to this module rather than the changes to your APM deployment. The errors you included appear to originate in the ElasticStack processing of data after it has been sent from the agent. Did the version of the APM change? If so, what were the versions before and after you moved to AWS?

**Comment by philkra** [comment]
i can only second @dstepe , this is not related to this module. make sure your version are compatible! aws never has the up to date elasticsearch version, so this very likely deployement conflict. you should use elastic‘s cloud services if you want to have the latest versions.

**Comment by philkra** [comment]
you should check out https://discuss.elastic.co/ for help

**Comment by philkra** [comment]
closing this because it is not related to this module
