### ISSUE TITLE
Elastic APM > 7.0 support

### ISSUE THREAD

**Issue by gomex** [philkra/elastic-apm-laravel#49]
I can't use my APM server version 7.0.

I am getting this error:

[2019-05-08 18:17:18] local.ERROR: GuzzleHttp\Exception\ClientException: Client error: `POST https://myserver.apm.us-east-1.aws.cloud.es.io/v1/transactions` resulted in a `404 Not Found` response: 404 page not found

According to this doc this endpoint was deprecated: https://www.elastic.co/guide/en/apm/server/7.0/transaction-endpoint.html

We need to change this endpoint request to event API: https://www.elastic.co/guide/en/apm/server/7.0/events-api.html

**Comment by dstepe** [comment]
This is really an issue with the supporting APM PHP package. Can you log this issue on that project?

https://github.com/philkra/elastic-apm-php-agent

I believe there was an plan to work on APM 7.0 compatibility, but I'm not sure what the status is.

**Comment by gomex** [comment]
Done: https://github.com/philkra/elastic-apm-php-agent/issues/77
