### ISSUE TITLE
Selecting .env data to send to the server

### ISSUE THREAD

**Issue by Ekion-1** [philkra/elastic-apm-laravel#52]
I've added the following to my configuration, but all of my `.env` variables are being sent to the server. I've tried placing the `env` parameter both inside and outside `app` (the documentation doesn't specify). Am I doing something wrong here?

```
return [
		// Sets whether the apm reporting should be active or not
		'active' => true,

		'app' => [
			// The app name that will identify your app in Kibana / Elastic APM
			'appName'    => 'APP-' . env('APP_ENV'),

			// The version of your app
			'appVersion' => '0.1',

			// Environment variables to send
			'env'        => ['APP_ENV'],

		],

// ... Rest of config
]
```

**Comment by dstepe** [comment]
What version of Laravel and the APM package are you using?

Can clarify how you added that to your configuration? Is that snippet from `elastic-apm.php` config file after publishing and updating?

From the what you provided, the first problem I see is that the `env` key is within the `app' key. That's not how the default configuration is structured:

https://github.com/philkra/elastic-apm-laravel/blob/master/config/elastic-apm.php

**Comment by Ekion-1** [comment]
I'm running Laravel 5.7 and
```
philkra/elastic-apm-laravel            5.7.4              A package to integrate Elastic APM into La...
philkra/elastic-apm-php-agent          6.2.2              A php agent for Elastic APM
```

I've also moved the `env` key to within the `env` key as specified by the documentation but all env variables are still being sent to the server.

```
<?php

	return [
		// Sets whether the apm reporting should be active or not
		'active' => true,

		'app' => [
			// The app name that will identify your app in Kibana / Elastic APM
			'appName'    => 'APP-' . env('APP_ENV'),

			// The version of your app
			'appVersion' => '0.1',

		],

		'env' => [
			// whitelist environment variables OR send everything
			'env' => ['APP_ENV']
			//'env' => []
		],

		'server' => [
			// The apm-server to connect to
			'serverUrl'   => 'elk1:8200',

			// Token for x
			'secretToken' => null,

			// API version of the apm agent you connect to
			'apmVersion'  => 'v1',

			// Hostname of the system the agent is running on.
			'hostname'    => gethostname(),],

		'spans' => [
			// Depth of backtraces
			'backtraceDepth' => 25,

			// Add source code to span
			'renderSource'   => true,

			'querylog' => [
				// Set to false to completely disable query logging, or to 'auto' if you would like to use the threshold feature.
				'enabled'   => true,

				// If a query takes longer then 200ms, we enable the query log. Make sure you set enabled = 'auto'
				'threshold' => 200,],],];
```

**Comment by dstepe** [comment]
I think you need to update your versions of the APM packages. The behavior you are experiencing appears to be present in releases up through 6.3.x:

https://github.com/philkra/elastic-apm-php-agent/blob/6.2.2/src/Events/EventBean.php#L200

Is there a reason you are not updating the the latest releases?

**Comment by dstepe** [comment]
@AlexGodbehere where you able to upgrade and if so, did it address your issue?

**Comment by Ekion-1** [comment]
@dstepe This was an oversight on my part. I had locked this package to an old version by mistake. All working now, thanks!
