### ISSUE TITLE
Need to register ElasticApmServiceProvider in Lumen 5.5.*

### ISSUE THREAD

**Issue by YuZhenXie** [philkra/elastic-apm-laravel#56]
Would it be better to add following information in README because Lumen doesn't support package discovery which Laravel does? Without this, it can't work in Lumen.

#### Register Service Provider
```
...
$app->register(\PhilKra\ElasticApmLaravel\Providers\ElasticApmServiceProvider::class);
...
```

*Tested Lumen version: 5.5.*

**Comment by philkra** [comment]
sure, please open a PR for this and we'll merge
