### ISSUE TITLE
POST /intake/v2/events resulted in a `400 Bad Request Client error: validating JSON document against schema

### ISSUE THREAD

**Issue by YuZhenXie** [philkra/elastic-apm-laravel#58]
This issue is found when I used [pull request #82](https://github.com/philkra/elastic-apm-php-agent/pull/82) in my project. The root cause is in [listeningForQueries](https://github.com/philkra/elastic-apm-laravel/blob/master/src/Providers/ElasticApmServiceProvider.php#L193).
Sometimes `$query->sql` is not string type but `Illuminate\Database\Query\Expression` at least in Lumen 5.5*. 
I tested it with string casting and no problem. What do you think about it?

**Comment by dstepe** [comment]
The mentioned pull request was merged some time ago.
