### ISSUE TITLE
How do I setup config

### ISSUE THREAD

**Issue by RammusXu** [philkra/elastic-apm-laravel#6]
Hi,

I'm a newbie of laravel and elastic stack. I already setup by README, but i don't know how to setup my serverUrl. Can you give me more hint or keyword to search?

**Comment by philkra** [comment]
No problem! Please check this in the repo: https://github.com/philkra/elastic-apm-laravel/blob/master/config/elastic-apm.php
Place this file in Laravel's `config` folder and adapt your changes. That's it :slightly_smiling_face:

**Comment by RammusXu** [comment]
Thank you.

It's will be nice to add it in README. 😄
