### ISSUE TITLE
Is it possible to see full stack trace at transaction page ?

### ISSUE THREAD

**Issue by abicur** [philkra/elastic-apm-laravel#60]
Is it possible using this package to display the full stack trace of the endpoint in transaction page?
Right now it displaying only this:
![image](https://user-images.githubusercontent.com/40180391/63844654-fe026c00-c9a1-11e9-9ee8-9da0b61ead39.png)

But I want to see full stack trace of this endpoint. 

Thank you for your help.

**Comment by philkra** [comment]
closing as repo is going to be archived.
