### ISSUE TITLE
Support for v2

### ISSUE THREAD

**Issue by jasperjorna** [philkra/elastic-apm-laravel#63]
Hi @philkra,

Awesome project, can't wait to implement this.

I noticed you tagged a new RC release in https://github.com/philkra/elastic-apm-php-agent.
When can we expect a release on the Laravel package?

**Comment by philkra** [comment]
Would you be interested in adding a PR that pulls in the `v2` agent?

**Comment by phroggyy** [comment]
@philkra I'm happy to do it once the new agent is out of RC and tagged as v7.0.0. I've forked it for now to use with rc3 anyway, so should be straightforward.

I have just noticed, however, that there is no way to set a timestamp, which means for the query log spans, the start time will always be off by `$query->time`. Think we could add a `setTimestamp` or some other way to override that per span? What about setting the timestamp from the `start()` method? And just like with `stop()`, allow passing in an argument to set it.

**Comment by zenire** [comment]
I was wondering if some of you already looked into this?

**Comment by phroggyy** [comment]
@ZeNiRe yes, we maintain a Laravel 5.8- and agent v7-compatible fork on https://github.com/jobilla/elastic-apm-laravel until agent v7 is in a stable release.

Regarding me previous comment about the inability to set a span's start time, there is now an agent PR to support that https://github.com/philkra/elastic-apm-php-agent/pull/121

**Comment by dstepe** [comment]
This package is transitioning to a new organization. We're interested in feedback and contributions. Please see this issue regarding testing the new package:

https://github.com/nipwaayoni/elastic-apm-laravel/issues/11

**Comment by philkra** [comment]
closing as repo is going to be archived.
