### ISSUE TITLE
Support Laravel 6

### ISSUE THREAD

**Issue by jblotus** [philkra/elastic-apm-laravel#64]

**Comment by Ekion-1** [comment]
Is Laravel 6 support planned? Would a PR be accepted?

**Comment by philkra** [comment]
I'm looking for someone to takeover this project, if you are interested, create a fork and I'm happily redirecting to your project

**Comment by Ekion-1** [comment]
I don't have the capacity to support this full time but I could potentially create a PR for Laravel 6.

**Comment by Ekion-1** [comment]
https://github.com/philkra/elastic-apm-laravel/pull/65 created.

**Comment by jblotus** [comment]
@philkra are you looking for a maintainer for this laravel package only or does this include the agent package as well?

I don't really have a ton of time like all of us but we do use this in production at work so perhaps I could help.

**Comment by philkra** [comment]
@jblotus only the for this package. I'm more than grateful for someone to takeover this package :)

**Comment by G89Angel** [comment]
https://github.com/philkra/elastic-apm-laravel/pull/68 should be merged too if I'm not wrong

**Comment by mfairch** [comment]
#68 has been merged and completes Laravel 6 support.

**Comment by jblotus** [comment]
yay
