### ISSUE TITLE
Missing function setSpans

### ISSUE THREAD

**Issue by BernhardtD** [philkra/elastic-apm-laravel#66]
The drop of the function `Transaction::setSpans` in the used package `elastic-apm-php-agent` causes a call to undefined method in the case not the latest version of this package is used, e.g. the previous version 5.8.2

From my point of view the version of  `elastic-apm-php-agent` in the composer.json should be stated like ^6.5.3 to get a compatible package.

**Comment by chali5124** [comment]
same issue 
```
"laravel/framework": "5.7.*",
"philkra/elastic-apm-laravel": "^5.8.2",
"philkra/elastic-apm-php-agent": "^7.0.0-rc2",
```

**Comment by CHOMNANP** [comment]
Same issue here.

**Comment by CHOMNANP** [comment]
Is there anyway, I can fix this manually in my project?

**Comment by dstepe** [comment]
This package is transitioning to a new organization. We're interested in feedback and contributions. Please see this issue regarding testing the new package:

https://github.com/nipwaayoni/elastic-apm-laravel/issues/11

**Comment by philkra** [comment]
closing as repo is going to be archived.
