### ISSUE TITLE
Laravel 5.7 support

### ISSUE THREAD

**Issue by Ekion-1** [philkra/elastic-apm-laravel#7]
Do you have any plans to update this to support Laravel 5.7?

**Comment by philkra** [comment]
Yes, an update should be available soon. I haven't fully checked the impact yet, but the upgrade guide https://laravel.com/docs/5.7/upgrade does not state any critical show stoppers.

**Comment by Ekion-1** [comment]
Great. @JustSteveKing has a fork that has 5.7.* in the composer dependencies and I can't see many changes. I look forward to the update.

**Comment by JustSteveKing** [comment]
Submitted a PR after testing this, no issues found with 5.7 but I didn't expect any tbh!
