### ISSUE TITLE
How to deal with curl errors in middleware

### ISSUE THREAD

**Issue by jblotus** [philkra/elastic-apm-laravel#9]
Hi there! I'm trying this package out and I noticed that when I have connection issues with the APM server the entire application will crash with something like the following:

`
GuzzleHttp \ Exception \ ConnectException
cURL error 7: Failed to connect to 1.1.1.1 port 8200: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
`

I would think that I don't want the application to go down completely because it can't communicate with the APM. Wrapping in a try catch seems to help:

```php
     try {
            ElasticApm::captureThrowable($exception);
            ElasticApm::send();
        } catch (\Throwable $ex) {
            Log::error($ex);
        }
```

Just wanted to pass this tip along

**Comment by philkra** [comment]
thank you James, that does make sense and should be implemented in the near future! I'll keep this thread alive until this behavior is implemented

**Comment by philkra** [comment]
Opened PR #13 for this issue
